services:
  web:
    build: ./newp
    restart: always
    ports:
      - "3000:80"
    environment:
      NODE_ENV: development
    networks:
      - app-network
  api:
    build: ./cars-api
    restart: always
    environment:
      DB_HOST: 192.168.109.118
      DB_USER: pn
      DB_PASS: 4321
      DB_DATABASE: newproject
      PORT: 3333
    ports:
      - "3333:3333"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge