services:
  web:
    build: ./newp
    restart: always
    ports:
      - "3000:80"
    networks:
      - app-network
  api:
    build: ./cars-api
    restart: always
    environment:
      DB_HOST: 192.168.149.230
      DB_USER: test
      DB_PASS: 4321
      DB_DATABASE: carservice
      PORT: 3333
    ports:
      - "3333:3333"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge